name: Test
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Main
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: main }
    - name: List files
      run: ls
